### ISSUE TITLE
NEG => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#12]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **structure fct** => paramètre entrée / sortie 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#LL11-L11C54
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/12#issuecomment-1520747807
- [x] => **mémoire dynamique** => utilisation / utilité ?!
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L24
=> voir réponse https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/12#issuecomment-1520747807
- [x] => test / condition => utilité ? 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#LL25-L28C3
=> voir réponse https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/12#issuecomment-1520747807
- [ ]

**Comment by Larssno** [comment]
1. le code complètement changé (j'avais rien compris) : voir le code dans les fichiers

**Comment by Larssno** [comment]
1. voici le code (juste) et terminé:
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/6485ee806598f9165cefec5cd38097a659d60fc4/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L11
2. l'utilisation de cette mémoire ne sert complètement a rien voir lien du dessus.

3. cette partie :
if (!demoPonDiv->tbValRes)
	{
		return;
	}
n'a pas son utilité pour le code.

**Comment by PBYetml** [comment]
OKI -> issue peut être fermée
