### ISSUE TITLE
CFO => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#14]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **structure fct** => paramètre entrée / sortie + indentation 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#L9
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#LL28-L39C3
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#LL9-L39C3
- [x] => **test / condition** => paramètre de test + structure + algorithme 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#L17
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#LL17-L25C26
- [x] => **variable / pointeur** => MAJ + type 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#L28
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#LL30C15-L30C25
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#L25
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#L37
- [ ] =>

**Comment by CyrilFeliciano** [comment]
1. Voici comment j'aurais du faire la structure de ma fonction:
void InitInfoPontDiviseur(pontDiviseur* demoPontDiv)     // fonction information pont diviseur
les paramètres d'entrée/sortie dépendent du CDC. Dans mon cas, j'ai un point de référence de type "pontDiviseur" ayant comme nom "demoPontDiv.

2. 

3.

**Comment by PBYetml** [comment]
Review de points 

1. OK -> voir correctif sur le fichier source [fonctionPontDiv.c](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/main/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c)  mis à jour : 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/1944965f7f1c341b85528555559079bf721dd60a/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#L6

2. OK - voir solution complète implémentée dans le fichier source  [fonctionPontDiv.c](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/main/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c) mis à jour
