### ISSUE TITLE
MBR => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#15]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x]  => **structure fct** => paramètre entrée / sortie 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#L15
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/15#issuecomment-1520546364
- [x] => **donnee utilisateur** => gestion de type => algorithme + MAJ structure 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#L26
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#L55
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/15#issuecomment-1520546364
- [x] => **gestion cst numérique** => hardcoding 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#L42
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/15#issuecomment-1520546364
- [ ] => **affichage utilisateur** => cst numérique
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#L44
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/15#issuecomment-1520546364
- [x] => **test / condition** => algorithme 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#LL42-L49C3
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/15#issuecomment-1520546364
- [x] => structure => MAJ des champs / déclaration 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#L72
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/15#issuecomment-1520546364
- [ ]

**Comment by MathieuBucher** [comment]
1. On doit l'écrire de cette manière avec les bons paramètre d'entrée qui pointe dans la structure : void InitInfoPontDiviseur(pontDiviseur* demoPontDiv)

2. il faut mettre %d car c'est un entier rentrer la valeur dans la structure scanf("%d", &demoPontDiv->nbDeResistance);

3.	while(i < demoPontDiv->nbDeResistance)
	{
		printf("Veuillez entrer la valeur de la résistance %d\n", i);
		scanf("%f", &demoPontDiv->valeurResistance[i]);

		if ((demoPontDiv->valeurResistance[i] > valMaxResistance) || (demoPontDiv->valeurResistance[i] < valMinResistance))
		{
			printf("La valeur entrée n'est pas dans les limites (minimum %f et maximum %f)\n", valMinResistance, valMaxResistance);
		}
		else
		{
			i++;
		}
	}

4. printf("Veuillez entrer la valeur de la résistance %d\n", i);

5.voir partie 3

6. voir partie 3

**Comment by PBYetml** [comment]
Pour le point 4. 

OKI -> vous proposez une autre solution; mais si je veux utiliser votre première instruction : 

``C
 printf("Veuillez insérer une valeur de résistance allant de 0.1 à 10Mohm pour R% : ",i);
``
qu'est-ce que vous devez corriger pour que cette instruction fonctionne ?

**Comment by MathieuBucher** [comment]
printf("Veuillez insérer une valeur de résistance allant de %f à %f Ohm pour R%d : ", valMinResistance, valMaxResistance, i);
________________________________
De : Philippe Bovey ETML ES ***@***.***>
Envoyé : jeudi 27 avril 2023 08:49
À : PBYetml/PROG_SLO1_C_PRJ2 ***@***.***>
Cc : Mathieu Bucher ***@***.***>; Assign ***@***.***>
Objet : Re: [PBYetml/PROG_SLO1_C_PRJ2] MBR => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur (Issue #15)


Pour le point 4.

OKI -> vous proposez une autre solution; mais si je veux utiliser votre première instruction :

C printf("Veuillez insérer une valeur de résistance allant de 0.1 à 10Mohm pour R% : ",i);
qu'est-ce que vous devez corriger pour que cette instruction fonctionne ?

**Comment by PBYetml** [comment]
OKI -> issue fermée => reste encore 2

**Comment by MathieuBucher** [comment]
Pour les 2 autres issues j'ai rajouté directement dans mon code que j'ai push sur le git
________________________________
De : Philippe Bovey ETML ES ***@***.***>
Envoyé : mercredi 10 mai 2023 15:30
À : PBYetml/PROG_SLO1_C_PRJ2 ***@***.***>
Cc : Mathieu Bucher ***@***.***>; Assign ***@***.***>
Objet : Re: [PBYetml/PROG_SLO1_C_PRJ2] MBR => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur (Issue #15)


OKI -> issue fermée => reste encore 2
