### ISSUE TITLE
JAR => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#16]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **gestion librairie (include)** => règles 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#LL15-L16C20
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/16#issuecomment-1505607502
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/a9336c16b342c5265f894311c5b5c67f231caf0f/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#LL16-L1720
- [x] => **gestion donnée utilisateur** => fct scanf + variable=> opérateur de conversion + type 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L34
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L54
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L65
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/16#issuecomment-1505634457
- [x] => **affichage utilisateur** => fct printf => opérateur de conversion 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L39
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L58
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L70
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/16#issuecomment-1505635426
- [x] => test / condition => double itération => algorithme => simplification 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#LL47-L61C3
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/16#issuecomment-1505651999
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/main/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#LL54C1-L69C35
- [ ]

**Comment by JeremyETMLES** [comment]
J'ai inclus la librairie stdio.h à la ligne 17, pour que le prinf et le scanf fonctionnent bien.

**Comment by JeremyETMLES** [comment]
Les & ne sont pas les bons caractères, je les ai donc remplacé par des %
