### ISSUE TITLE
MPT => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#17]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **structure** => déclaration variable + utilisation champs 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MPT/PROJET1_S2_PERRET/PROJET1_S2_PERRET/fonctionsPontDiv.c#L16
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MPT/PROJET1_S2_PERRET/PROJET1_S2_PERRET/fonctionsPontDiv.c#LL18-L25C3
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/2ad5714ccbf9dc078b82ae55db88cd0ed5e6ff73/MPT/PROJET1_S2_PERRET/PROJET1_S2_PERRET/fonctionsPontDiv.c#LL30-L37C3
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/17#issuecomment-1520415573
- [ ]

**Comment by Melissaperret** [comment]
Pour ma dernière fonction je n'avais pas écris avec la forme scientifique, de plus je lisais la valeur aux bornes des résistances, j'ai rajouté un complément pour connaitre la tension entre les résistances. De plus j'ai rajouté la tension GND pour connaitre le sens des tensions : 

void AffichageTensionPontDiviseur(str_pontDiviseur demoPontDiv)
{
	int indexResistance;
	int indexTensionVs;
	for (indexResistance = 0; indexResistance < demoPontDiv.nbResistances; indexResistance++)
	{
		printf("Tension sur la resistance R%d vaut %.2e[V]\n", indexResistance + 1, demoPontDiv.tb_tensionAuBornes[indexResistance]);
	}
	printf("\n");

	for (indexTensionVs = 0; indexTensionVs < demoPontDiv.nbResistances; indexTensionVs++)
	{
		if (((demoPontDiv.nbResistances - 1) - indexTensionVs) == 0)
		{
			printf("Tension sur la tension GND vaut %.2e[V]\n", demoPontDiv.tb_tentionEntreResistances[indexTensionVs]);
		}
		else
		{
			printf("Tension sur la tension VS%d vaut %.2e[V]\n", ((demoPontDiv.nbResistances - 1) - indexTensionVs), demoPontDiv.tb_tentionEntreResistances[indexTensionVs]);
		}
	}
}

**Comment by PBYetml** [comment]
OKI, bien pour l'adaptation et l'amélioration du code !!!
