### ISSUE TITLE
LMS => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#18]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **gestion des librairies (headerfile)** => règles
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#LL10-L11C20
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/18#issuecomment-1513990503
- [x] => **structure fct** => paramètre entrée/sortie => type 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#LL13-L13C53
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/18#issuecomment-1513992395
- [x] => **gestion donnée utilisateur** => fct scanf => opérateur de conversion 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#L21
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#L36
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#L54
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/18#issuecomment-1513994908
- [x] => **gestion structure** => MAJ des champs 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#LL22-L28C4
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#LL55-L62C4
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/18#issuecomment-1520474771
- [ ]

**Comment by LeoMendesEsEtml** [comment]
Les issues on été corrigée. dans InitInfoPontDiviseur

**Comment by LeoMendesEsEtml** [comment]
Les issues on été corrigée. dans InitInfoPontDiviseur

**Comment by PBYetml** [comment]
voir le commentaire fait dans l'issue #3 -> c'est pour cela que je re rouvre les 3 issues close

**Comment by LeoMendesEsEtml** [comment]
Réponse pour "=> gestion des librairies (headerfile) => règles" : 
 
 J'ai retirer les includes non nécessaire

**Comment by LeoMendesEsEtml** [comment]
Moddification de => structure fct => paramètre entrée/sortie => type : 

void InitInfoPontDiviseur(pontDiviseur* demoPontDiv)

**Comment by LeoMendesEsEtml** [comment]
=> gestion donnée utilisateur => fct scanf => opérateur de conversion : 
 
 Les paramètre on été modifié avec des %"paramètre correspondant" de plus une gestion d'erreur à été ajoutée afin d'éviter les warning de visual studio concernat ces scanf
 
 if (scanf("%d", &valUser) != 1)
{};

if (scanf("%f", &valRes) != 1) 
{};

if (scanf("%d", &valTension) != 1)
{};

**Comment by LeoMendesEsEtml** [comment]
=> gestion structure => MAJ des champs : 
 		
 		if (scanf("%d", &valUser) != 1)
		{};
		if (valUser > nbrMaxRes) {
			valUser = nbrMaxRes;
		}
		else if (valUser <= 0) {
			valUser = DEFAULTMINRES;
		}
 
 		
 		if (valTension > maxTension) {
			valTension = maxTension;
		}
		else if (valTension < 1) {
			valTension = DEFAULTVMIN;
		}
		else {}

**Comment by LeoMendesEsEtml** [comment]
Nouveau fichier fonctionnel et corriger disponible sur la Branche  "LMS" ainsi que sur mon dépôt

**Comment by PBYetml** [comment]
dans votre réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/18#issuecomment-1513996055

on voit pas comment vous mettez à jour la structure reçu en paramètre, comparé à votre premier code, merci de mettre un exemple

**Comment by LeoMendesEsEtml** [comment]
Voici un exemple de comment je met a jour la structure : 

demoPontDiv->vAlim = valTension;

**Comment by PBYetml** [comment]
OKI => on peut fermer cette issue
