### ISSUE TITLE
DBS => bugs/remarques => fichier fonctionPontDiv.c -> InitInfoPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#19]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **déclaration fct** => paramètre entrée / sortie => demande du CDC 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L13
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/19#issuecomment-1495507848
- [x] => **gestion donnée utilisateur** => fct scanf => opérateur de conversion 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L17
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L28
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/19#issuecomment-1495509446
- [x] => structure => MAJ des champs => voir le CDC 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L20
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L25
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L31
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/d4faeb85ee04f95c03cafb333ac440d883bd73c5/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L36
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/19#issuecomment-1495510677
- [ ]

**Comment by damienbignens** [comment]
point1 : void InitInfoPontDiviseur(str_pontDiviseur* pt_demoPontDiv)

**Comment by damienbignens** [comment]
point 2: 	
        int valeur;
	printf("\n veuillez inserer le nombre de resistance possible dans votre pont diviseur:");
	scanf_s("%d", &valeur);

	scanf_s("%d", &valeur);

**Comment by damienbignens** [comment]
point 3: 
void InitInfoPontDiviseur(str_pontDiviseur* pt_demoPontDiv)
{
	int valeur;
	printf("\n veuillez inserer le nombre de resistance possible dans votre pont diviseur:");
	scanf_s("%d", &valeur);
	while ((getchar() != '\n') && (getchar() != EOF));
	if (valeur > NB_MAX_resistance)
	{
		valeur = NB_MAX_resistance;
	}
	else if (valeur <= 0)
	{
		valeur = 1;
	}
	pt_demoPontDiv -> com_resistance = valeur;
	int i;
	for (i = 0; i < valeur; i++)
	{
		printf("Veuillez inserer une valeur de resistance allant de %1.1lf a %.0lfMohm pour R%d:", VAL_MIN_resistance, VAL_MAX_resistance / 10e6, i + 1);
		scanf_s("%lf", &pt_demoPontDiv->tb_valeur_R[i]); 
		while ((getchar() != '\n') && (getchar() != EOF));
		if (pt_demoPontDiv->tb_valeur_R[i] < VAL_MIN_resistance || pt_demoPontDiv->tb_valeur_R[i] > VAL_MAX_resistance)
		{
			printf("!!! Erreur de valeur !!! \n");
			i--;				 
		}
	}

	printf("Veuillez inserer la tension d'alimentation du montage :");
	scanf_s("%d", &valeur);
	while ((getchar() != '\n') && (getchar() != EOF));

	if (valeur > TENSION_MAX)
	{
		valeur = TENSION_MAX;
	}
	else if (valeur < 1)
	{
		valeur = 1;
	}
	pt_demoPontDiv->alime = valeur; //Stock la valeur dans la variable tensionAlimVe
}

**Comment by damienbignens** [comment]
elle été nul je l'ai changer 
printf("Veuillez inserer une valeur de resistance allant de 0.1 a 10Mohm pour R%d:", i + 1);
