### ISSUE TITLE
DBS => fichier PontResistifs.h -> remarques

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#2]
voici un listing des points à améliorer dans le fichier `PontResistifs.h`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => gestion des define / constante => 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/40908fa8dbec23fed33f19e9f83b31d8e1d6d9a1/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/PontResistifs.h#L14
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/2#issuecomment-1518028273
- [x] => gestion de structure => **y en a pas :(** => voir la donnée du cdc !!!
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/2#issuecomment-1499162416
- [x] => gestion des prototypes => paramètre In/out => types utilisé 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/40908fa8dbec23fed33f19e9f83b31d8e1d6d9a1/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/PontResistifs.h#LL20-L22C53
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/2#issuecomment-1495430994
- [ ]

**Comment by damienbignens** [comment]
point 1 #define VAL_MAX_resistance 10000000

**Comment by damienbignens** [comment]
point2 :  
typedef struct
{
	int com_resistance;
	int alime;
	double tb_valeur[NB_MAX_resistance];
	double tb_bornes_resistance [NB_MAX_resistance];
}str_pontDiviseur;

**Comment by damienbignens** [comment]
point3 : 
void InitInfoPontDiviseur(str_pontDiviseur* pt_demoPontDiv);
void CalculTensionPontDivisueur(str_pontDiviseur* pt_demoPontDiv);
void AffichageTensionPontDivisueur (str_pontDiviseur* pt_demoPontDiv);

**Comment by PBYetml** [comment]
> 

Y a-t-il un autre moyen d'écrire la valeur `10000000` sans se tromper de 0 ?

**Comment by PBYetml** [comment]
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/2#issuecomment-1495430580

=> attention pour la déclaration de tableau dans une structure dans un headerfile -> en théorie cela serait juste mais en pratique vous ne pouvez pas faire ceci à cause des constantes/define 
`double tb_valeur_R[NB_MAX_resistance];
double tb_bornes_resistance [NB_MAX_resistance];`

voir article sur le discord : [tableau et constante dans une headerfile](https://discordapp.com/channels/706248600912658567/706251985250156575/967516638570229800)

**Comment by damienbignens** [comment]
point2,2 
typedef struct
{
	int com_resistance;
	int alime;
	double tb_valeur_R[10];
	double tb_bornes_resistance[10];
}str_pontDiviseur;

**Comment by PBYetml** [comment]
Regardez mon commentaire https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/2#issuecomment-1495554353, vous n'y répondez pas encore 

que va faire la déclaration suivante : `#define VAL_MAX_resistance 10*10e6` que représente `10e6`

**Comment by damienbignens** [comment]
10e6 représente 10 puissance 6 = 1'000'000 
je l'ai noté en notation ingénieur   
#define VAL_MAX_resistance 10*10e6 // ca va definire VAL_MAX_resistance a une valeur de 10*10^6

**Comment by PBYetml** [comment]
OKI cette fois ;)
