### ISSUE TITLE
DBS => bugs/remarques => fichier fonctionPontDiv.c -> fct CalculTensionPontDivisueur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#22]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **structure d'une fct** => paramètre d'entrée / sortie => voir la donnée du cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/97db004fa9550c4105d7a857605eeaef1dfec1e8/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L42
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/22#issuecomment-1495511783
- [x] => algorithme => somme => boucle / itération + lecture de tableau => voir la donnée du cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/97db004fa9550c4105d7a857605eeaef1dfec1e8/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#LL48-L50C63
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/22#issuecomment-1520408151
- [ ]

**Comment by damienbignens** [comment]
point 1 ; 
void CalculTensionPontDivisueur(str_pontDiviseur* pt_demoPontDiv)

**Comment by damienbignens** [comment]
point 2 : 
{
	double sommeResistances = 0;  
	int i;
	for (i = 0; i < pt_demoPontDiv->com_resistance; i++)
	{
		sommeResistances = pt_demoPontDiv->tb_valeur_R[i] + sommeResistances;
	}

	int e;  //Index
	double tensionResistance_n; //variable pour VpontRu
	for (e = 0; e < pt_demoPontDiv->com_resistance; e++)
	{
		tensionResistance_n = pt_demoPontDiv->alime * (pt_demoPontDiv->tb_valeur_R[e] / sommeResistances);		//tensionResistanceU = VpontRu
		pt_demoPontDiv->tb_bornes_resistance[e] = tensionResistance_n;
	}
}

**Comment by PBYetml** [comment]
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/22#issuecomment-1495512185
```C: 
tensionResistance_n = pt_demoPontDiv->alime * (pt_demoPontDiv->tb_valeur_R[e] / sommeResistances);
```
êtes-vous sur de calculer la tension de chaque point milieu de votre pont résistif => pas sur ;) -> faut encore revoir votre algorithme

**Comment by damienbignens** [comment]
j'ai fais come melisa je calcule chaque résistance entre les borne

**Comment by PBYetml** [comment]
Etes-vous sur que c'est vraiment ca cela ? Malheureusement votre algorithme ne fonctionne pas si vous voulez calculer la tension en aux borne de chaque résistances => ici vous devez faire de toute manière une addition de plusieurs résistances sur le numérateur... prenez le cas d'un pont résistif à 3 résistances, calculez les points de tensions U1 et U2 ([voir schéma](https://www.swisstransfer.com/d/31b96921-bc7c-463b-9c58-269996317a76)) regardez si vous arrivez a en tirer une formule générique ;)

**Comment by damienbignens** [comment]
point 2 :
{
double sommeResistances = 0;
char U_tot
int i;
for (i = 0; i < pt_demoPontDiv->com_resistance; i++)
{
sommeResistances = pt_demoPontDiv->tb_valeur_R[i] + sommeResistances;
}

int e;  //Index
double tensionResistance_n; //variable pour VpontRu
for (e = 0; e < pt_demoPontDiv->com_resistance; e++)
{
	pt_demoPontDiv->tb_bornes_resistance[e] = pt_demoPontDiv->alime * (pt_demoPontDiv->tb_valeur_R[e] / sommeResistances)	;
}
for (i = 0; i < pt_demoPontDiv->com_resistance; i++) 
U_tot += pt_demoPontDiv->tb_bornes_resistance[i]; 
demoPontDiv->tb_bornes_resistance[i] = pt_demoPontDiv ->alime - U_tot ;
}
}

**Comment by damienbignens** [comment]
pour le calcule j'ais fais comme vous le voulais en laisse mon encien version dans les calcule il fais donc les 2 
void CalculTensionPontDivisueur(str_pontDiviseur* pt_demoPontDiv)
{
	double sommeResistances = 0;  
	double EnretResistances = 0;
	int i;
	for (i = 0; i < pt_demoPontDiv->com_resistance; i++)
	{
		sommeResistances = pt_demoPontDiv->tb_valeur_R[i] + sommeResistances;
	}

	int e;  //Index
	double tensionResistance_n; //variable pour VpontRu
	for (e = 0; e < pt_demoPontDiv->com_resistance; e++)
	{
		tensionResistance_n = pt_demoPontDiv->alime * (pt_demoPontDiv->tb_valeur_R[e] / sommeResistances);		//tensionResistanceU = VpontRu
		pt_demoPontDiv->tb_bornes_resistance[e] = tensionResistance_n;
	}
	EnretResistances = sommeResistances ; 
	for (e = 0; e < pt_demoPontDiv->com_resistance; e++)
	{
		EnretResistances -= pt_demoPontDiv->tb_valeur_R[e];
		pt_demoPontDiv->tb_v_Entre_Resistances[e] = pt_demoPontDiv->alime * (EnretResistances / sommeResistances);

	}


}
