### ISSUE TITLE
MPT => bugs/remarques => fichier fonctionPontDiv.c -> fct CalculTensionPontDivisueur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#24]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => algorithme => somme de résistance => boucle / itération => voir formule du CDC
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/24#issuecomment-1520426764
- [x] => algorithme => calcul d'une tension sur un pont résistif => voir formule du CDC
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/97db004fa9550c4105d7a857605eeaef1dfec1e8/MPT/PROJET1_S2_PERRET/PROJET1_S2_PERRET/fonctionsPontDiv.c#LL30-L37C3
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/24#issuecomment-1520426764
- [ ]

**Comment by Melissaperret** [comment]
j'ai cru qu'on devait refaire la même fonction que la première. j'avais mal compris la donnée 

je calcul également la tension entre les résistances 

voici ce que j'aurai du faire :

void CalculTensionPontDiviseur(str_pontDiviseur* pt_demoPontDiv)
{
double sommeResistances = 0; //correspond à mon diviseur
int indexResistances;
for (indexResistances = 0; indexResistances < pt_demoPontDiv->nbResistances; indexResistances++)
{
sommeResistances = pt_demoPontDiv->tb_valResistances[indexResistances] + sommeResistances;
}

int u;  //Index
double tensionBorneResistance; //variable pour VpontRu
for (u = 0; u < pt_demoPontDiv->nbResistances; u++)
{
	tensionBorneResistance = pt_demoPontDiv->tensionAlimVe * (pt_demoPontDiv->tb_valResistances[u] / sommeResistances);		//tensionResistanceU = VpontRu
	pt_demoPontDiv->tb_tensionAuBornes[u] = tensionBorneResistance;
}

int indexTension;
double resistances = sommeResistances;
for (indexTension = 0; indexTension < pt_demoPontDiv->nbResistances; indexTension++)
{
	resistances -= pt_demoPontDiv->tb_valResistances[indexTension];		//la variable résistance correspond aux résistance qui seront au numérateur de la formule 
	pt_demoPontDiv->tb_tentionEntreResistances[indexTension] = pt_demoPontDiv->tensionAlimVe * (resistances / sommeResistances);   //Calcul du pont diviseur 
}

**Comment by PBYetml** [comment]
OKI -> bien pour l'upgrade de la fonction ;)
