### ISSUE TITLE
JAR => bugs/remarques => fichier fonctionPontDiv.c -> fct CalculTensionPontDivisueur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#25]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [ ] => algorithme => tension aux différents point du pont => calcul => somme des résistances => boucle / itération => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/97db004fa9550c4105d7a857605eeaef1dfec1e8/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L99
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/25#issuecomment-1527128641
- [ ]

**Comment by PBYetml** [comment]
Si vous regardez l'exemple du cdc, il est fait mention les points milieu du pont résistif - mais effectivement il y aurait un point à améliorer, car la donnée porte à confusion sur la tension aux bornes des résistances (!!! **ce que votre algorithme ne calcul pas** !!!) et la tension aux différents points milieu (!!! **à nouveau ce que votre algorithme ne fait** !!!) - donc cette issue est toujours **ouverte** -> le but est de comprendre l'algorithme, selon la formule mathématique donnée !!!

**Comment by JeremyETMLES** [comment]
J'ai modifié le calcul de la tension des résistances pour qu'il calcul le point en dessus. J'ai modifié l'affichage en conséquence pour qu'il affiche la tension au borne de chaque résistance.

**Comment by JeremyETMLES** [comment]
Calcul: https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/77098fb67c9e46062e33fc41b139db9163f92492/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L103-L119
Affichage: https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/77098fb67c9e46062e33fc41b139db9163f92492/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/fonctionsPontDiv.c#L130-L141

**Comment by PBYetml** [comment]
OKI -> issue fermée
