### ISSUE TITLE
CFO => bugs/remarques => fichier fonctionPontDiv.c -> fct CalculTensionPontDivisueur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#27]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **structure d'une fct** => paramètre d'entrée / sortie => voir la donnée du cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/97db004fa9550c4105d7a857605eeaef1dfec1e8/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/fonctionsPontDiv.c#L42
- [x] => **algorithme** => somme de résistance => boucle / itération => voir formule du CDC 
- [x] =>  **algorithme** => calcul d'une tension sur un pont résistif => voir formule du CDC

**Comment by CyrilFeliciano** [comment]
1. Voici comment j'aurais du faire la structure de ma fonction:
void InitInfoPontDiviseur(pontDiviseur* demoPontDiv)     // fonction Information pont diviseur
les paramètres d'entrée/sortie dépendent du CDC. Dans mon cas, j'ai un point de référence de type "pontDiviseur" ayant comme nom "demoPontDiv.

2. Je n'ai pas fais l'algorithme du CDC. Voici comment j'ai calculé ma résistance total:
void CalculTensionPontDiviseur(pontDiviseur* demoPontDiv)
{
	//Déclaration des variables locales
	float res_total = 0;
	char i = 0;

	for (i = 0; i < demoPontDiv->Nb_Res; i++)
	{
		res_total = res_total + demoPontDiv->ValRes[i];
	}
3. Voici comment j'ai calculé la tension sur un pont résistif:
for (i = 0; i < demoPontDiv->Nb_Res; i++)
	{
		demoPontDiv->Val_U_Res[i] = demoPontDiv->Vin * demoPontDiv->ValRes[i] / res_total;
	}

**Comment by PBYetml** [comment]
Validation des points à revoir 

1. OK 
2. OK
3. NOT OK -> comme discuté -> ici vous n'avez n'y la tension aux bornes de chaque résistance, n'y sur les points milieu de pont - prenez un pont résisif de 3 résistances 1k 2k 3k... calculez à la main, la tension aux bornes de chaque résistance et les points milieu, regardez si vous arrivez au même résultat que votre itération proposé en point 3 
```c: 
for (i = 0; i < demoPontDiv->Nb_Res; i++)
{
  demoPontDiv->Val_U_Res[i] = demoPontDiv->Vin * demoPontDiv->ValRes[i] / res_total;
}
```

**Comment by PBYetml** [comment]
Review des points de validations : 

3. OK
