### ISSUE TITLE
NEG => bugs/remarques => fichier fonctionPontDiv.c -> fct CalculTensionPontDivisueur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#29]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **structure d'une fct** => paramètre d'entrée / sortie => voir la donnée du cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/97db004fa9550c4105d7a857605eeaef1dfec1e8/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L31
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/29#issuecomment-1520754020
- [x] => **algorithme** => somme de résistance => boucle / itération => voir formule du CDC 
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/29#issuecomment-1520754020
=> voir réponse complète ici : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/29#issuecomment-1531010399
- [x] =>  **algorithme** => calcul d'une tension sur un pont résistif => voir formule du CDC 
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/29#issuecomment-1520754020
=> voir réponse complète ici : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/29#issuecomment-1531010399

**Comment by PBYetml** [comment]
voir commentaire dans la réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/9#issuecomment-1520409399

**Comment by Larssno** [comment]
1. voici la fonction faite et (juste): 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/6485ee806598f9165cefec5cd38097a659d60fc4/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L75


2. réponse du point: 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/6485ee806598f9165cefec5cd38097a659d60fc4/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L85


3. réponse du point: 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/6485ee806598f9165cefec5cd38097a659d60fc4/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L91


4. un autre algorithme (merci de l'aide de Cyril) pour calculer entre les résistances:
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/6485ee806598f9165cefec5cd38097a659d60fc4/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L91

**Comment by PBYetml** [comment]
en relation avec votre réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/29#issuecomment-1520754020

2. pour que votre instruction soit complètement juste qu'est-ce qui manque ou que vous ne mentionnez pas ? et à quoi vous sert cette instruction  
3. même remarque ou question supplémentaire ? quelle différence entre le point 3 et 4 ? que cherchez-vous à calculer ?

**Comment by Larssno** [comment]
2.  for (i = 0; i < demoPonDiv->nbResComposantPonRes; i++)
	{
		restotal = restotal + demoPonDiv->tbValRes[i];
	}

3. et 4. for (i = 0; i < demoPonDiv->nbResComposantPonRes; i++)
	{
		demoPonDiv->tbValTensionRes[i] = (demoPonDiv->tensionAlimPontRes * demoPonDiv->tbValRes[i]) / restotal;
	}
	for (i = 0; i < demoPonDiv->nbResComposantPonRes; i++)
	{
		ValTensionResTot = ValTensionResTot + demoPonDiv->tbValTensionRes[i];
		demoPonDiv->ValTensionEntreRes[i] = demoPonDiv->tensionAlimPontRes - ValTensionResTot;
	}

**Comment by PBYetml** [comment]
OKI => issue fermée
