### ISSUE TITLE
NEG => bugs/remarques => fichier fonctionPontDiv.c -> fct AffichageTensionPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#32]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => voir issue #29 => point 1 => structure d'une fct => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L35
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/32#issuecomment-1520759904
- [ ] => **structure** => lecture de champs 
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/32#issuecomment-1531021234
- [ ] => **affichage utilisateur** => donnée + affichage scientifique => voir le cdc 
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/32#issuecomment-1531021234

**Comment by Larssno** [comment]
pareil au point précèdent: voir code après modification

**Comment by Larssno** [comment]
1. voici la fonction (juste) : 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/6485ee806598f9165cefec5cd38097a659d60fc4/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/fonctionsPontDiv.c#L101

2. ici il me manquait le nombre de tableau voici la modification :
typedef struct {
	unsigned char nbResComposantPonRes;
	unsigned char tensionAlimPontRes;
	float tbValRes [10];
	float tbValTensionRes [10];
	float ValTensionEntreRes[10];
}PontDiviseur;

**Comment by PBYetml** [comment]
selon votre réponse https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/32#issuecomment-1520759904

au point 2, vous ne répondez pas à la question !! comment lisez-vous les champs de la structure et surtout lesquels seront utilisés dans cette fonction

**Comment by Larssno** [comment]
2.
void affichageTensionPontDiviseur(PontDiviseur demoPonDiv)
{
	// Déclaration des variables locales
	int i = 0;

	// Affichage de la chute de tension sur chaque résistance
	for (i = 0; i < demoPonDiv.nbResComposantPonRes; i++)
	{
		printf("Chute de tension sur la resistance %d: %.2eV\n", i +1, demoPonDiv.tbValTensionRes[i]);
	}
	// Affichage de la chute de tension entre chaque résistance
	for (i = 0; i < demoPonDiv.nbResComposantPonRes; i++)
	{
		printf("Valeur de la tension au point VF %d: %.2eV\n", i + 1, demoPonDiv.ValTensionEntreRes[i]);
	}
}
on appel la structure avec PontDiviseur et on utilise ses variable nbResComposantPonRes, tbValTensionRes, ValTensionEntreRes.

**Comment by PBYetml** [comment]
OKI => issue fermée
