### ISSUE TITLE
KAN => bugs/remarques => fichier fonctionPontDiv.c -> fct AffichageTensionPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#33]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => voir issue #28  => point 1 => structure d'une fct => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/KAN/Project1_S2_Allemann/fonctionsPontDiv.c#L52
- [x] => **structure** => lecture de champs 
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/33#issuecomment-1542869993
- [x] => **affichage utilisateur** => donnée + affichage scientifique => voir le cdc 
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/33#issuecomment-1542869993

**Comment by Kevin-AllemannETML-ES** [comment]
Modification et ajout cohérent de la fonction d'affichage en fonction du CDC

**Comment by PBYetml** [comment]
voir la réponse faites ici : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/28#issuecomment-1541478544

**Comment by Kevin-AllemannETML-ES** [comment]
Voici la fonction d'affichage

https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/ab6aba36a58f7906b4d941faed25e3ec37dd33e9/KAN/Project1_S2_Allemann/fonctionsPontDiv.c#LL93C2-L100C2

**Comment by PBYetml** [comment]
=> issue fermée
