### ISSUE TITLE
CFO => bugs/remarques => fichier fonctionPontDiv.c -> fct AffichageTensionPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#34]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => structure fct => pas implémentée => voir le CDC 
- [x] => **structure** => lecture de champs 
- [x] => **affichage utilisateur** => donnée + affichage scientifique => voir le cdc

**Comment by damienbignens** [comment]
void CalculTensionPontDivisueur(str_pontDiviseur* pt_demoPontDiv)
{
	double sommeResistances = 0;  
	int i;
	for (i = 0; i < pt_demoPontDiv->com_resistance; i++)
	{
		sommeResistances = pt_demoPontDiv->tb_valeur_R[i] + sommeResistances;
	}

	int e;  //Index
	double tensionResistance_n; //variable pour VpontRu
	for (e = 0; e < pt_demoPontDiv->com_resistance; e++)
	{
		tensionResistance_n = pt_demoPontDiv->alime * (pt_demoPontDiv->tb_valeur_R[e] / sommeResistances);		//tensionResistanceU = VpontRu
		pt_demoPontDiv->tb_bornes_resistance[e] = tensionResistance_n;
	}
}

**Comment by damienbignens** [comment]
void AffichageTensionPontDivisueur(str_pontDiviseur pt_demoPontDiv)
{
	int i;
	for (i = 0; i < pt_demoPontDiv.com_resistance; i++)
	{
		printf("Tension sur la resistance R%d vaut %1.3lf[V]\n", i + 1, pt_demoPontDiv.tb_bornes_resistance[i]);
	}
}

**Comment by PBYetml** [comment]
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/34#issuecomment-1495514545

regardez le cdc => on vous demande une notation scientifique, avec quelle opérateur pouvez-vous le faire, si ce n'est pas `%f ` 
``C: 
printf("Tension sur la resistance R%d vaut %1.3lf[V]\n", i + 1, pt_demoPontDiv.tb_bornes_resistance[i]);
``

**Comment by CyrilFeliciano** [comment]
Voici comment j'aurais du faire la déclaration de ma fonction affichage :
void AffichageTensionPontDiviseur(pontDiviseur demoPontDiv)
{
	//Déclaration des variables locales
	char i = 0;

	for (i = 0; i < demoPontDiv.Nb_Res; i++)
	{
		printf("Chute de tension sur la resistance %d: %.2eV\n", i, demoPontDiv.Val_U_Res[i]);
	}

}
Pour la notation scientifique j'ai fais "%.2e".
