### ISSUE TITLE
MBR => bugs/remarques => fichier fonctionPontDiv.c -> fct AffichageTensionPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#35]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => voir issue #28  => point 1 => structure d'une fct => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/MBR/PROJET1_S2_BUCHER/PROJET1_S2_BUCHER/fonctionsPontDiv.c#L87
=> voir reponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/35#issuecomment-1520555472
- [x] => **structure** => lecture de champs 
=> voir reponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/35#issuecomment-1520555472
- [x] => **affichage utilisateur** => donnée + affichage scientifique => voir le cdc 
=> voir reponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/35#issuecomment-1520555472

**Comment by MathieuBucher** [comment]
Voici la nouvelle fonction :
void AffichageTensionPontDiviseur(pontDiviseur demoPontDiv)
{
	//fonction affichant la tension se trouvant sur chaque résistance avec 3 chiffres significatif

	unsigned char i = 0;

	for (i = 0; i < demoPontDiv.nbDeResistance; i++)
	{
		printf("La tension sur la résistance %d: %.2ev \n", i, demoPontDiv.valeurTension[i]);
	}
}

%.2ev permet d'afficher 2 chiffres significatifs après la virgule

**Comment by PBYetml** [comment]
OKI -> issue fermée
