### ISSUE TITLE
LMS => bugs/remarques => fichier fonctionPontDiv.c -> fct AffichageTensionPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#38]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => voir issue #23 => point 1 =>structure d'une fct => voir la donnée du cdc
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#L73
- [x] => **structure** => lecture de champs 
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/38#issuecomment-1513998549
- [x] => **boucle / itération** => champs
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/38#issuecomment-1513998549
- [x] => **affichage mode console** => opérateur d'affichage 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/fonctionsPontDiv.c#L77
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/38#issuecomment-1513998549
- [ ]

**Comment by LeoMendesEsEtml** [comment]
=> voir issue https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/23 => point 1 =>structure d'une fct => voir la donnée du cdc : 
=> structure => lecture de champs
 => boucle / itération => champs
 => affichage mode console => opérateur d'affichage
 
 void AffichageTensionPontDiviseur(pontDiviseur demoPontDiv) {
	int i;
	for (i = 0; i < demoPontDiv.nbrRes; i++) {
		printf("\nTension sur la resistance R%d vaut : %.3e", i+1 , demoPontDiv.tab_ValTension[i]);
	}
}

**Comment by LeoMendesEsEtml** [comment]
Nouveau fichier fonctionnel et corriger disponible sur la Branche  "LMS" ainsi que sur mon dépôt

**Comment by PBYetml** [comment]
OKI -> répondu et corrigé les différents points demandés
