### ISSUE TITLE
DBS => bugs/remarques => fichier fonctionPontDiv.c -> fct AffichageTensionPontDiviseur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#39]
voici un listing des points à améliorer/corriger dans le fichier `fonctionPontDiv.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **structure d'une fct** => paramètre entrée sortie => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L56
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/39#issuecomment-1499171488
- [x] => **structure** => lecture de champs 
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/39#issuecomment-1499171488
- [x] => **affichage utilisateur** => boucle / itération + donnée + affichage scientifique => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/PROJET1_S2_DAMIEN_BIGNENs/fonctionsPontDiv.c#L56
voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/39#issuecomment-1518080510
- [ ]

**Comment by damienbignens** [comment]
void AffichageTensionPontDivisueur(str_pontDiviseur pt_demoPontDiv)
{
	int i;
	for (i = 0; i < pt_demoPontDiv.com_resistance; i++)
	{
		printf("Tension sur la resistance R%d vaut %1.3lf[V]\n", i + 1, pt_demoPontDiv.tb_bornes_resistance[i]);
	}
}

**Comment by PBYetml** [comment]
voir https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/39#issuecomment-1499171488

si vous regardez le cdc, on vous demande une notation scientifique => est-ce que l'opérateur de conversion `%1.3lf `permet une représentation scientifique ?

**Comment by damienbignens** [comment]
pour la notation scientifique  je dois utiliser %.2e
printf("Tension sur la resistance R%d vaut %.2e[V]\n", i + 1, pt_demoPontDiv.tb_bornes_resistance[i]);

**Comment by PBYetml** [comment]
OKI, c'est good cette fois ;)
