### ISSUE TITLE
DBS => bugs/remarques => fichier mainProje1_S2.c 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#41]
voici un listing des points à améliorer/corriger dans le fichier `mainProjet1_S2.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => voir issue #2  => point2 =>gestion de structure => implémentation => globale plusieurs fichier / global un seul fichier / local 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/mainProjet1_S2.c#LL35-L41C3
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/41#issuecomment-1495515202
- [x] => **appel de fct** => paramètre entrée / sortie => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/mainProjet1_S2.c#L62
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/DBS/PROJET1_S2_DAMIEN_BIGNENS/PROJET1_S2_DAMIEN_BIGNENs/mainProjet1_S2.c#L66
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/41#issuecomment-1495515202
- [ ]

**Comment by damienbignens** [comment]
void main()
{
	//-- déclaration de variables --// 
	char choixUser = 0; 

	//-- déclaration de structure --// 
	str_pontDiviseur str_valeur;

	//-- boucle permettant de savoir si l'utilisateur veut continuer ou pas --// 
	do
	{
		//-- appel de fonction
		//-- insertion de valeur de résistance pour le pont divisueur de tension --//
		InitInfoPontDiviseur(&str_valeur);

		//-- calcul de la tension sur chaque résistance du pont diviseur --// 

		CalculTensionPontDivisueur(&str_valeur);
		
		//-- afficahge de la tension sur chaque pont diviseur --// 

		AffichageTensionPontDivisueur(str_valeur);

		printf("\nVoulez-vous quitter le programme ? [o/n]"); 
		scanf_s("%c", &choixUser); 

		//-- s'assure que le buffer est vider pour refaire une nouvelle demande --//
		while ((getchar() != '\n') && (getchar() != EOF));
		
	} while (!(choixUser == 'o' || choixUser == 'O')); 


	//pause du programme//
	system("pause");
}
