### ISSUE TITLE
LMS => bugs/remarques => fichier mainProje1_S2.c

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#42]
voici un listing des points à améliorer/corriger dans le fichier `mainProjet1_S2.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [ ] => voir issue #3   => point2 =>gestion de structure => implémentation => globale plusieurs fichier / global un seul fichier / local 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/mainProjet1_S2.c#LL44-L49C4
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1520500508
- [x] => **appel de fct** => paramètre entrée / sortie => voir le cdc 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/mainProjet1_S2.c#L56
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/mainProjet1_S2.c#L59
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/LMS/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/PROJET1_S2_LEO_MENDES/mainProjet1_S2.c#L62
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1520493600
- [ ]

**Comment by PBYetml** [comment]
voir le commentaire fait dans l'issue #3 -> c'est pour cela que je re rouvre les 3 issues close

**Comment by LeoMendesEsEtml** [comment]
=> voir issue https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/3 => point2 =>gestion de structure => implémentation => globale plusieurs fichier / global un seul fichier / local : 

La structure étant utilisé dans le fichier "fonctionsPontDiv.c" la déclaration a été effectuée dans le fichier .h afin qu'elle soie accessible

**Comment by LeoMendesEsEtml** [comment]
=> appel de fct => paramètre entrée / sortie => voir le cdc : 
		//-- calcul de la tension sur chaque résistance du pont diviseur --// 
		CalculTensionPontDiviseur(&Pontdiviseur1);

		//-- afficahge de la tension sur chaque pont diviseur --// 
		AffichageTensionPontDiviseur(Pontdiviseur1);

**Comment by LeoMendesEsEtml** [comment]
Nouveau fichier fonctionnel et corriger disponible sur la Branche  "LMS" ainsi que sur mon dépôt

**Comment by PBYetml** [comment]
en relation avec réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1514001791

Qu'avez-vous du implémenter dans le fichier source -> ici le main, pour utiliser la structure déclarée dans le headerfile. L'implémentation est correcte, mais votre explication ne l'est pas 

Vous avez deux implémenter deux choses dans le fichier source : **`mainProjet1_S2.c`**, qu'est-ce que c'est ?

**Comment by PBYetml** [comment]
en relation avec votre réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1514002553

y a encore un appel de fct que vous n'avez pas mentionné !!!

**Comment by LeoMendesEsEtml** [comment]
> en relation avec votre réponse : [#42 (comment)](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1514002553)
> 
> y a encore un appel de fct que vous n'avez pas mentionné !!!

		//-- insertion de valeur de résistance pour le pont divisueur de tension --//
		InitInfoPontDiviseur(&Pontdiviseur1);

		//-- calcul de la tension sur chaque résistance du pont diviseur --// 
		CalculTensionPontDiviseur(&Pontdiviseur1);

		//-- afficahge de la tension sur chaque pont diviseur --// 
		AffichageTensionPontDiviseur(Pontdiviseur1);

**Comment by LeoMendesEsEtml** [comment]
> en relation avec réponse : [#42 (comment)](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1514001791)
> 
> Qu'avez-vous du implémenter dans le fichier source -> ici le main, pour utiliser la structure déclarée dans le headerfile. L'implémentation est correcte, mais votre explication ne l'est pas
> 
> Vous avez deux implémenter deux choses dans le fichier source : **`mainProjet1_S2.c`**, qu'est-ce que c'est ?

J'ai implémenter le fichier PontResistifs.h afin qu'il soie utilisable dans le main

//-- librairie personnelle --//                                                                                                                                                                                                                                                                                                                  
#include "PontResistifs.h"

**Comment by PBYetml** [comment]
En relation à votre réponse https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1520500508

Il manque encore une indication, vous avez associé la librairie très bien, mais que devez-vous faire avec la structure déclarée dans le headerfile ? 

Un dernier petit effort avant que cette issue soit fermée ;)

**Comment by LeoMendes1407** [comment]
La structure dois être déclarée en globale en définissant un type de struct pontDiviseur
typedef struct 
{
	int nbrRes;	//Nombre de resistance dans le ponts resistif (R1-Rn)
	int vAlim;	//Tension d'alimentation du pont resistif
	float tab_ValRes[10]; // Valeur des resistance
	float tab_ValTension[10]; // Potentiel au borne de chaque resistance
}pontDiviseur;

**Comment by PBYetml** [comment]
en réponse à votre commentaire : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/42#issuecomment-1539730206

ca pourrait être une réponse quasi correct, mais il manque encore une information -> par convention ou déclare-t-on un typedef (structuc / enum / union) et ici pour faire sens au cdc ?

**Comment by LeoMendes1407** [comment]
définir un raccourci pour une structure, une union ou une énumération en utilisant la déclaration "typedef". Cela permet de donner un nom plus court et plus facile à comprendre à ces éléments, ce qui peut rendre le code plus clair et facile à lire. 

Cette déclaration peut être faite dans le fichier d'en-tête où ces éléments sont définis, ou dans le fichier source qui les utilise. 

Dans notre cas il doit être définie dans le fichier header

**Comment by PBYetml** [comment]
OKI -> issue fermée
