### ISSUE TITLE
CFO => bugs/remarques => fichier mainProje1_S2.c

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#45]
voici un listing des points à améliorer/corriger dans le fichier `mainProjet1_S2.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **implémentation de librairie** => standard / personnelle => **pas implémentée :(**
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/mainProjet1_S2.c#L27
- [x] => **structure** => déclaration => **pas implémentée :(**
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/mainProjet1_S2.c#L41
- [x] => **appel de fct** =>  **pas implémentée :(**
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/mainProjet1_S2.c#LL48-L54C60
- [ ]

**Comment by CyrilFeliciano** [comment]
1. Je n'ai pas implémenté de librairies personnelle. Voici comment j'aurais du faire:
//-- librairie personnelle --// 
#include "PontResistifs.h"

2. Voici comment j'aurais du déclarer ma structure:
//-- déclaration de structure --// 
	pontDiviseur ValPontDiviseur;

3. Je n'ai pas implémentée les 3 appels de fonction. Voici comment j'aurais du faire les appels:
//-- appel de fonction
		//-- insertion de valeur de résistance pour le pont divisueur de tension --//
		InitInfoPontDiviseur(&ValPontDiviseur);

		//-- calcul de la tension sur chaque résistance du pont diviseur --// 
		CalculTensionPontDiviseur(&ValPontDiviseur);

		//-- affichage de la tension sur chaque pont diviseur --// 
		AffichageTensionPontDiviseur(ValPontDiviseur);

**Comment by PBYetml** [comment]
Validation des différents points à revoir : 

1. OK 
2. OK -> voir votre réponse dans l'issue #7 -> point 4 
3. OK 

N'oubliez pas après soit d'updater votre propre branche ou de faire un pull request pour updater la branche main
