### ISSUE TITLE
NEG => bugs/remarques => fichier mainProje1_S2.c

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#47]
voici un listing des points à améliorer/corriger dans le fichier `mainProjet1_S2.c`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => **gestion de fichier** => chemin d'accès => **!!! attention !!!**
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/47#issuecomment-1520763941
- [x] => **structure** => déclaration => **pas implémentée :(**
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/mainProjet1_S2.c#L41
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/47#issuecomment-1520763941
- [x] => **appel de fct** =>  **pas implémentée :(**
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/56340c26353aeec3f015e17ee6cdc814693cc236/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/mainProjet1_S2.c#LL47-L54C60
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/47#issuecomment-1520763941
- [ ]

**Comment by Larssno** [comment]
1. le chemin d'accès a été vérifié (promis c'est bon cette fois si)
2. Structure implémenté...
3. appel de fct implémenté...

**Comment by PBYetml** [comment]
OKI -> issue fermée
