### ISSUE TITLE
JAR => fichier PontResistifs.h -> bugs/remarques

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#5]
voici un listing des points à améliorer/corriger dans le fichier `PontResistifs.h`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => define / cst => écriture 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/40908fa8dbec23fed33f19e9f83b31d8e1d6d9a1/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/PontResistifs.h#LL22-L22C56
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/5#issuecomment-1505596208
- [x] => macro => surdéfinition 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/40908fa8dbec23fed33f19e9f83b31d8e1d6d9a1/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/PontResistifs.h#LL26-L35C22
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/5#issuecomment-1505577611
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/main/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/PontResistifs.h#LL26C1-L33C1
- [x] => cst numérique vs definition => utilisation 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/40908fa8dbec23fed33f19e9f83b31d8e1d6d9a1/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/PontResistifs.h#LL32-L33C73
- [x] => structure => tableau => type 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/40908fa8dbec23fed33f19e9f83b31d8e1d6d9a1/JAR/PROJET1_S2_AFFOLTER/PROJET1_S2_AFFOLTER/PontResistifs.h#L32
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/5#issuecomment-1505575070
- [ ]

**Comment by JeremyETMLES** [comment]
J'ai modifié le type du tableau pour les valeur de résistance en float à la ligne 30 pour qu'il correspondent au cahier des charges

**Comment by JeremyETMLES** [comment]
La différence entre une constante et une définition est que la définition est changée lors de la compilation dans la bonne dimension de variable, contrairement aux constantes. https://stackoverflow.com/questions/65571946/why-cant-i-use-a-constant-int-to-declare-an-array-and-initialize-it-in-c
