### ISSUE TITLE
LMS => Correction de la gestion des CST -> notion de static 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#57]
Correction de la gestion des CST

```C 
#ifndef FONCTIONS
#define FONCTIONS

// Définition
#define MAXRES 1e7...

//Déclaration de constante 
static const int nbrMaxRes = NBRMAXRES;
static const int maxTension = MAXTENSION; //en volt
static const double maxRes = MAXRES; //10 Mega Ohm
static const float minRes = MINRES; //1 Ohm

//-- déclaration de structure --// 
typedef struct 
{
...
}pontDiviseur;

//Prototype de fonctions 
void InitInfoPontDiviseur(pontDiviseur* demoPontDiv);
... 

#endif`
``` 
_Originally posted by @LeoMendesEsEtml in https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/3#issuecomment-1513977222_

Ici le problème est la notion de `**static** ` => qu'est-ce qu'il signifie en C ? 

=> issue en relation avec l'issue #3

**Comment by LeoMendesEsEtml** [comment]
on utilise "static" Lorsqu' appliqué à une variable à l'extérieur d'une fonction, il spécifie que la variable est visible uniquement dans le fichier où elle est déclarée.

et "extern" signifie  une variable à l'extérieur d'une fonction, il spécifie que la variable a une portée globale et peut être utilisée dans n'importe quel fichier source. 

Dans le cas de mon code j'aurais du utilisé extern

extern const int nbrMaxRes = NBRMAXRES;
extern const int maxTension = MAXTENSION; //en volt
extern const double maxRes = MAXRES; //10 Mega Ohm
extern const float minRes = MINRES; //1 Ohm

**Comment by PBYetml** [comment]
Aie !!! votre réponse pique un peu les yeux : 

Static : 
1. pour vous mettre sur le voie : est-ce que vous pouvez déclarer une variable en `**static** `et `**const**` dans un fichier source ou un headerfile [OUI / NON]
2. est-ce qu'une variable static a du sens en tant que variable globale [OUI / NON]
3. Où s'utilise la notion de static 

Extern : 
4. où se déclare une variable de type externe ? 
5. au niveau de la mémoire externe, comment cela fonctionne-t-il ?

**Comment by LeoMendes1407** [comment]
l'utilisation de "static" / "extern" : 
La réponce serait de ne pas utilser de static ou extern :
//Déclaration de constante
const int nbrMaxRes = 10;
const int maxTension = 30; //en volt
const double maxRes = 1e7; //10 Mega Ohm
const float minRes = 0.1; //1 Ohm

Mais suite à l'erreur LNK2005 : L'utilisation du extern ou const est nécéssaire afin de faire disparaitre cette erreur : 
https://stackoverflow.com/questions/13185751/what-is-the-difference-between-static-const-and-const#:~:text=const%20means%20that%20you%27re,be%20seen%20outside%20of%20it.

Une enumération aurais peu aussi fonctionner dans ce ca.


"Lorsque le compilateur fusionne les différents fichiers objets pour créer l'exécutable final, il rencontrera plusieurs définitions de ces mêmes variables, ce qui conduira à une erreur de lien (LNK2005) qui indique que la même variable est définie plusieurs fois.

Pour éviter cette erreur, il est recommandé de déclarer ces variables comme extern dans le header et de les définir dans un seul fichier source (.cpp) qui sera compilé et lié avec les autres fichiers objets. Cela permettra de s'assurer qu'il n'y a qu'une seule copie de chaque variable dans l'exécutable final. Par exemple :

Dans le fichier header :
extern const int nbrMaxRes;
extern const int maxTension;
extern const double maxRes;
extern const float minRes;

Dans un fichier source (.cpp) :
const int nbrMaxRes = 10;
const int maxTension = 30;
const double maxRes = 1e7;
const float minRes = 0.1;

Il est important de noter que les variables déclarées comme const ne peuvent pas être modifiées après leur initialisation.

Chaque fichier source qui inclurait ce header créerait sa propre copie de ces variables, ce qui entraînerait une erreur de lien (LNK2005) lors de la compilation et de la création de l'exécutable final, car il y aurait plusieurs définitions de ces mêmes variables.

En déclarant plutôt ces variables avec le mot clé "extern" dans le fichier header.
On indique que ces variables sont définies dans un autre fichier source et que leur adresse mémoire sera résolue lors de la liaison (linkage) entre les différents fichiers objets pour créer l'exécutable final.

En résumé, l'utilisation du mot clé "extern" permet de déclarer une variable dans un fichier header, sans la définir, afin de permettre à plusieurs fichiers source d'y accéder sans créer de conflits de définitions multiples.

"static" peut également être utilisé pour déclarer des variables dans un fichier header, mais dans ce cas, cela signifie que la variable a une portée de fichier et est visible uniquement à l'intérieur du fichier source dans lequel elle est déclarée. Cela signifie que chaque fichier source qui inclut le header verrait sa propre copie de la variable, tout comme avec une variable constante déclarée sans le mot clé "extern".
"

**Comment by PBYetml** [comment]
Top => très bonne explication => je vais placer ce fil (discussion) dans le discord -> ca fera référence à ce problème => good JOB !!
