### ISSUE TITLE
CFO => fichier PontResistifs.h -> bugs/remarques

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#7]
voici un listing des points à améliorer/corriger dans le fichier `PontResistifs.h`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] => inclure d'autres headerfile => règles 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PontResistifs.h#LL3-L5C65
voir le point 1 du commentaire de CFO -> https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/7#issuecomment-1512709980
- [x] => cst / definition => ERRATUM => !! **fonctionnelle ** !! => PBY => 02.04.2022
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PontResistifs.h#LL8-L11C39
voir lien discord => [keyword const en C -> voir lien discord](https://discordapp.com/channels/706248600912658567)
- [x] => déclaration de cst numérique => écriture 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PontResistifs.h#L10
- [x] => structure => globale vs local
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PontResistifs.h#LL16-L21C3
- [x] => variables / pointeur => utilité 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PontResistifs.h#LL24-L31C21
- [x] => prototype => paramètre entrée / sortie => voir le CDC
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PontResistifs.h#LL33-L33C60

=> listing du headerfile modifié avec réponse aux issues : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/main/CFO/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PROJET1_S2_Feliciano/PontResistifs.h-> GJ 👍

**Comment by CyrilFeliciano** [comment]
1. Les includes des librairies doivent se faire dans le main.c et pas dans le fichier header. Pour la ligne n°35, je devrai mettre tout ce qui est après le "endif" en commentaire.
2. Écrire les constantes de cette manière est juste mais cela dépend du compilateur. Pour "ValMin_Res" il faut enlever le "unsigned"", car cela n'existe pas en float. J'aurais pu les créer avec des define comme ceci:
#define MaxRes     10
#define MaxTension 30
#define ValMax_Res  10e6
#define ValMin_Res  0.1

3. J'aurais pu écrire la valeur en notation ingénieur comme ceci : 10e6
4. J'ai déclaré une structure local. Ce qui veut dire qu'elle ne peut être utilisé que dans ce fichier. J'aurais du la déclarer en global comme ça:
typedef struct
{
	unsigned char Nb_Res;
	unsigned char Vin;
	float ValRes[10];		
	float Val_U_Res[10];
}pontDiviseur;
5.
6. J'avais mal compris le CDC pour les prototypes de fonctions. Voici comment j'aurais du faire:
void InitInfoPontDiviseur(pontDiviseur* demoPontDiv);
void CalculTensionPontDiviseur(pontDiviseur* demoPontDiv);
void AffichageTensionPontDiviseur(pontDiviseur demoPontDiv);

**Comment by PBYetml** [comment]
validation de vos réponses 

1. OK 
2. OK
3. OK
4. OK 
6. OK 

il vous reste encore la question 5 -> et aussi de push votre solution soit en mode ligne de commande (git init / git add / ...) soit à l'aide d'un logiciel comme source tree ou à la "mano" en ajoutant votre fichier directement dans votre browser 

si jamais pour les lignes de commande un petit rappel ici : https://github.com/PBYetml/InfoGit

**Comment by PBYetml** [comment]
Pour le point 5 => auriez-vous un exemple pointeur de structure et lecture/écriture sur un de champs de celle-ci
