### ISSUE TITLE
NEG => fichier PontResistifs.h -> bugs/remarques

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_C_PRJ2#9]
voici un listing des points à améliorer/corriger dans le fichier `PontResistifs.h`

=> voir fichier vidéo [lien vidéo](https://github.com/PBYetml/PROG_SLO1_C_PRJ2/edit/main/retour%20vid%C3%A9o/Readme.md)

- [x] #50
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/PontResistifs.h#L1
voir lien discord => [C -> pragma](https://discordapp.com/channels/706248600912658567/706251985250156575/913915854360543233)
=> voir réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/9#issuecomment-1521370062
- [x] => directive include => utilisation 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/PontResistifs.h#L4
=> voir votre réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/9#issuecomment-1520055363
- [x] => cst / define => utilisation 
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/PontResistifs.h#LL8-L11C30
=> voir votre réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/9#issuecomment-1520055363
=> voir votre réponse . https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/9#issuecomment-1520741093
- [x] => variable/cst => écriture
https://github.com/PBYetml/PROG_SLO1_C_PRJ2/blob/f6c427ae89d9f4f420983950220da54f03862fe7/NEG/PROJET1_S1_ELGHANDOUR/PROJET1_S1_ELGHANDOUR/PontResistifs.h#LL10-L10C35
=> voir votre réponse : https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/9#issuecomment-1520055363
- [ ]

**Comment by PBYetml** [comment]
voir l'issue #50 faite par @Larssno

**Comment by Larssno** [comment]
1. j'ai compris et replacer le fichier au bon endroit.
2. J'ai supprimé le fichier qui est inutile pour le ce code, il peut servir pour l'inclusion multiple d'un même fichier d'en-tête.
3.  #include "PontResistifs.h" à bien été supprimé erreur bête de ma part xD d'avoir include dans le include en question.
4. Les constante on été changé avec des #define ( même si en compilent j'ai remarqué qu'avec const ça marche aussi ) et j'ai mis 10e6 a la place de 10000000 pour avoir quelque chose de plus propre.

**Comment by Larssno** [comment]
2. il ne faut jamais mettre un include d'en-tête dans un ficher d'en-tête, il peut etre mit et il faut pour ce code de le mettre dans les deux fichier .c

3. j'aurai du déclarer en define et non en const comme ici :
#define nombreMaxDeResPontDiv 10
#define tensionMaxPontDiv     30
#define valeurMaxRes          10e6  // pour avoir quelque chose de plus propre et pas un 10000000 il faut faire ca comme sur le define
#define valeurMinRes          0.1

**Comment by PBYetml** [comment]
Si vous regardez bien dans votre réponse https://github.com/PBYetml/PROG_SLO1_C_PRJ2/issues/9#issuecomment-1520741093

vous ne répondez pas au point 1 => ? qu'avez-vous fait

**Comment by Larssno** [comment]
j'ai supprimé  #pragma once

**Comment by PBYetml** [comment]
OKI -> issue fermée
